grep -i "enter" log2.txt | wc | awk '{print "app enter request  : " $1}'
grep -i "cancel query" log2.txt | wc | awk '{print "app cancel request   : " $1}'
grep -i "Obtaining new connection from the pool" log2.txt | wc | awk '{print "r2dbc-pool Obtaining new connection from the pool   : " $1}'
grep -i "DELIVER" log2.txt | wc | awk '{print "reactor-pool deliver poolslot   : " $1}'
grep -i "cancel deliver" log2.txt | wc | awk '{print "reactor-pool cancel deliver   : " $1}'
grep -i "aquired" log2.txt | wc | awk '{print "r2dbc-pool aquired   : " $1}'
grep -i "getConnection" log2.txt | wc | awk '{print "app usingWhen getConnection   : " $1}'
grep -i "Releasing connection PostgresqlConnection" log2.txt | wc | awk '{print "r2dbc-pool Releasing connection on close Connection   : " $1}'
grep -i "Releasing connection after cancellation" log2.txt | wc | awk '{print "r2dbc-pool Releasing connection after cancellation   : " $1}'
grep -i "Request Release" log2.txt | wc | awk '{print "reactor-pool Request Release   : " $1}'
grep -i "cleanup" log2.txt | wc | awk '{print "r2dbc-pool cleanup   : " $1}'
grep -i "received cancel signal" log2.txt | wc | awk '{print "r2dbc-pool received cancel signal   : " $1}'
grep -i "upstream cancel" log2.txt | wc | awk '{print "r2dbc-pool upstream cancel   : " $1}'
grep -i "CANCEL ACQUIRE" log2.txt | wc | awk '{print "reactor-pool CANCEL ACQUIRE   : " $1}'

